services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: ${CONTAINER_NAME}_postgres
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       PGDATA: ${PGDATA}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:${PGDATA}
    networks:
      - postgres_net

  subask:
    build:
      context: ./AskHub
      dockerfile: ./Dockerfile
    image: askhub_img
    restart: always
    container_name: ${CONTAINER_NAME}_askhub
    volumes:
      - ./AskHub/config/prod.yaml:/app/config/prod.yaml
    env_file:
      - ./AskHub/.env
    ports:
      - 8080:8080
    networks:
      - postgres_net
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
    postgres_net:
      driver: bridge