env: "prod"
storage_path: "host=postgres user=postgres password=root dbname=askhub port=5432 sslmode=disable"
local_path_storage: "./storage/"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s